#
# 保存配置数据。
# 很多配置选项都可以直接在命令行中进行设置，但是如果你把那些配置写在这儿，你就不用非要去记住那些命令了。
#

# 站点名称（显示在标题中）
name: 于乐涛

# 简短的简介或描述（显示在标题中）
description: 行百里者半九十

# 您的头像或个人资料图片的URL（您可以使用GitHub个人资料图片）
avatar: https://pic.rmb.bdstatic.com/64b0c1d1fa7e98ab60bce7781f98749c.jpeg

#
# 下面的标志是可选的
#

# 在您输入的每个用户名的页脚中包含一个图标
footer-links:
  dribbble:
  email: 2427142850@qq.com
  facebook:
  flickr:
  github: yeautto/yeautto.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # 只需在此处键入任何可工作的RSS图标
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # 您的个人资料用户名中位于plus.google.com之后的任何内容/


# 输入您的Disqus短名称（不是您的用户名）以启用对帖子的评论
# 您可以在Disqus帐户的“设置”页面上找到您的简称
disqus:

# 输入您的Google Analytics web跟踪代码（例如UA-2110908-2）以激活跟踪
google_analytics:

# 您的网站URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# 用于 Sitemap.xml and your RSS feed
url:

# 如果您在 GitHub pages上的项目存储库中托管站点为 (http://yourusername.github.io/repository-name)
# 而不是用户存储库 (http://yourusername.github.io)
# 那么就需要在这里添加baseurl，例如: "/repository-name"
baseurl: ""

#
# !! 您不需要更改下面的任何配置标志 !!
#

permalink: /:title/

# Jekyll的发布现在你正在使用
version: v1.2.0

# Jekyll 3现在只支持 Kramdown 的 Markdown
kramdown:
  # 使用 GitHub 风格 markdown, 包括三重反斜线围栏代码块
  input: GFM
  # Jekyll 3 and GitHub Pages now only support 用于语法突出显示的胭脂
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # 使用现有 pygments 语法突出显示css
    css_class: 'highlight'

# 设置Sass partials目录，因为我们正在使用@imports
sass:
  style: :expanded # 您可能更喜欢使用 :compressed

# 使用以下插件
gems:
  - jekyll-sitemap # 使用Jekyll官方网站地图 gem 创建网站地图
  - jekyll-feed #使 用官方Jekyll提要gem创建Atom提要

# 从生产站点中排除这些文件 _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
